name: Deploy API Terraform + Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      TF_VAR_gcp_credentials: terraform/gcp-key.json
      TF_VAR_project_id: ${{ secrets.GCP_ID_KEY }}
      TF_VAR_region: us-central1
      TF_VAR_vm_name: api-tarefas-vm
      TF_VAR_docker_image: mariaeduardazx/api-tarefas:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configurar autenticação GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_JSON_KEY }}

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_ID_KEY }}

      - name: Build e Push Docker
        run: |
          IMAGE="mariaeduardazx/api-tarefas:latest"
          docker build -t $IMAGE .
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          docker push $IMAGE

      - name: Criar arquivo de credenciais
        run: |
          echo '${{ secrets.GCP_JSON_KEY }}' > terraform/gcp-key.json

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve
